

 const productData = [{
     //------------- Men's Dress Shirts---------------
        _id: 1,
        name: "Alex Vando Mens Dress Shirts Wrinkle Free Regular Fit Stretch Bamboo Men Shirt",
        image: '/images/m.dress.shirts/black.jpeg',
        price: 24,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "The material is comfortable, breathable and not see through. It has a little spandex mix in so it stretches some which allows for some moving room."
    },
    {
        _id: 2,
        name: "Beninos Men's Slim Fit Solid Point Collar Button Down Dress Shirts",
        image: '/images/m.dress.shirts/blue.jpg',
        price: 25,
        size: "M",
        color: "Light Blue",
        countInStock: 20,
        description: "DESIGN: Perfect fit, one chest pocket, turn down collar, this long sleeve button down dress shirt characterized by plaid pattern on collar, sleeves and front, modern and stylish."
    },
     {
        _id: 3,
        name: "Alimens & Gentle French Cuff Regular Fit Dress Shirts (Cufflink Included)",
        image: '/images/m.dress.shirts/cyan.jpg',
        price: 35,
        size: "M",
        color: "Cyan",
        countInStock: 20,
        description: "OCCASIONS: This stylish mens button down shirts can be worn tucked or untucked pairing, are perfect for Party, Business, Work, Holiday, Travel, Casual, or Daily Life/ you can match with Flat Front, Chino Pants, Jeans, Cargo Pants."
    },
    {
        _id: 4,
        name: "Cloudstyle Mens Paisley Shirt Long Sleeve Dress Shirt Button Down Casual Regular Fit",
        image: '/images/m.dress.shirts/purple.jpeg',
        price: 30,
        size: "L",
        color: "Purple",
        countInStock: 20,
        description: "SIZE: Size are US standard size, please choose your size according to our size chart (Not the Amazon Size Chart) and if you have big belley and wide shoulders, we recommend you to go up one size."
    },
    {
        _id: 5,
        name: "Alex Vando Mens Dress Shirts Regular Fit Long Sleeve Men Shirt",
        image: '/images/m.dress.shirts/red.jpg',
        price: 30,
        size: "L",
        color: "Red",
        countInStock: 20,
        description: "FABRIC: Wicking cotton fabric helps evaporate moisture, offers you great hand feel, skin friendly, very comfortable to wear."
    },
    {
        _id: 6,
        name: "Jack Martin - Club/Penny Collar - Blue Bengal Stripe Slim Fit Shirt. Mens 1920s Blinders Gang Shirts",
        image: '/images/m.dress.shirts/redstripe.jpg',
        price: 45,
        size: "L",
        color: "White",
        countInStock: 20,
        description: "GUARANTEE: Suitable for hand and machine wash at 30 degrees, hold up well after washing. Kindly wash it before wearing."
    },
    {
        _id: 7,
        name: "Alimens & Gentle French Cuff Regular Fit Dress Shirts (Cufflink Included)",
        image: '/images/m.dress.shirts/white.jpeg',
        price: 30,
        size: "L",
        color: "White",
        countInStock: 20,
        description: "US STANDARD SIZE: Our dress shirts are made based on USA standard size. This business shirt is regular fit cut."
    },
    {
        //------------------------Men's Pants--------------------------------

        _id: 8,
        name: "Men's Expandable Waist Classic-Fit Flat-Front Dress Pants",
        image: "/images/m.pants/bluestripe.jpg",
        price: 30,
        size: "L",
        color: "Navy",
        countInStock: 20,
        description: "An expandable waist guarantees a perfect fit in these classic-fit dress pants with flat-front styling."
    },
    {
        _id: 9,
        name: "Perry Ellis Men's Modern Fit Performance Pant",
        image: "/images/m.pants/class.jpeg",
        price: 25,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "Modern fit – The sleek and classic look that you’ve been looking for. The modern fit pants sit at the waist with a trim fit through the hips and thighs and the pants feature a slightly-tapered leg opening."
    },
    {
        _id: 10,
        name: "Men's American Chino Flat Front Straight Fit Pant",
        image: "/images/m.pants/grey.jpg",
        price: 25,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Straight fit chino features a straight leg with zip fly and button closure.Wrinkle-free and machine washable to wear straight from the dryer."
    },
    {
        _id: 11,
        name: "Goodthreads Men's Slim-Fit Wrinkle-Free Comfort Stretch Dress Chino Pant",
        image: "/images/m.pants/navy.jpg",
        price: 50,
        size: "L",
        color: "Navy",
        countInStock: 20,
        description: "Wrinkle-free, easy-care flat front dress chino in a cotton twill with stretch elastane for comfort."
    },
    {
        _id: 12,
        name: "Classic-fit Wrinkle-Resistant Flat-Front Dress Pant fit by DXL",
        image: "/images/m.pants/red.jpg",
        price: 45,
        size: "L",
        color: "Red",
        countInStock: 20,
        description: "This classic-fit flat-front dress pant is crafted from a wrinkle-resistant 100% polyester and features a continuous comfort mechanism allowing the waistband to stretch up to four inches."
    },
    {
        _id: 13,
        name: "Calvin Klein Men's Slim Fit Dress Pant",
        image: "/images/m.pants/style.jpeg",
        price: 135,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Ready to wear. Arrives with a finished hemmed to avoid extra tailoring.Tailored around your body's natural silhouette."
    },
    {
        _id: 14,
        name: "Dockers Men's Classic Fit Easy Khaki Pants (Regular and Big & Tall)",
        image: "/images/m.pants/tan.png",
        price: 60,
        size: "L",
        color: "Tan",
        countInStock: 20,
        description: "Eased Fit Through Seat and Thigh, Sits at Waist With a Straight Leg.No Wrinkle Men's Khaki Pants With Stretch for Performance."
    },
    //-------------------------------Men's Shoes------------------------------
    {
        _id: 15,
        name: "Bruno Marc Men's Formal Leather Lined Dress Shoes",
        image: "/images/m.shoes/black.jpg",
        price: 70,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "Breathable leather linings and leather-covered cushioned latex footbed for all-day comfort."
    },
    {
        _id: 16,
        name: "MERRYLAND Men's Casual Lace Up Oxford Shoes",
        image: "/images/m.shoes/blue.jpg",
        price: 65,
        size: "M",
        color: "Blue-Grey",
        countInStock: 20,
        description: "Soft footbed and comfortable lining for additional support and comfort."
    },
    {
        _id: 17,
        name: "DREAM PAIRS Bruno Marc Moda Italy Men's Prince Classic Modern Dress Shoes",
        image: "/images/m.shoes/brown.jpg",
        price: 40,
        size: "L",
        color: "Brown",
        countInStock: 20,
        description: "Made of carefully selected leather, it is breathable and comfortable to wear, and the folding resistance of leather which could keep the elegant shoe shape."
    },
    {
        _id: 18,
        name: "FRASOICUS Men’s Dress Shoes with Genuine Leather in Classic Brogue Elastic Band Oxford Formal Shoes for Men",
        image: "/images/m.shoes/classy.jpg",
        price: 45,
        size: "M",
        color: "Black",
        countInStock: 20,
        description: "The Inside and outside of this shoe has a hidden elastic band design, it is more fashionable and easier to wear."
    },
    {
        _id: 19,
        name: "FRASOICUS Men’s Dress Shoes with Genuine Leather in Classic Brogue Elastic Band Oxford Formal Shoes for Men",
        image: "/images/m.shoes/cowboy.jpg",
        price: 55,
        size: "M",
        color: "Brown",
        countInStock: 20,
        description: "Made of carefully selected leather, it is breathable and comfortable to wear, and the folding resistance of leather which could keep the elegant shoe shape."
    },
    {
        _id: 20,
        name: "ALIPASINM Men’s Dress Shoes with Genuine Leather in Cap-Toe Classic Formal Style Shoes for Men",
        image: "/images/m.shoes/fly.jpg",
        price: 30,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "Hand-painted leather men shoes, has elegant color and good quality. Has High-density rubber soles which are more flexible."
    },
    {
        _id: 21,
        name: "STACY ADAMS Men's Pierce Moe-Toe Slip-on Penny Loafer",
        image: "/images/m.shoes/old.jpg",
        price: 45,
        size: "L",
        color: "Burgandy",
        countInStock: 20,
        description: "CLASSIC STYLE: Smooth leather apron toe penny loafer featuring braided loops and classic strap."
    },
    //-------------------------Mens Shorts-----------------------------------
    {
        _id: 22,
        name: "Men's Classic-Fit 9-12 Short",
        image: "/images/m.shorts/black.jpg",
        price: 45,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "A no-nonsense basic flat-front short that's clean-cut and versatile enough for the weekend, vacation, or any day."
    },
    {
        _id: 23,
        name: "Dockers Men's Perfect Short",
        image: "/images/m.shorts/blue.jpg",
        price: 20,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Sits at waist, roomy fit through seat and thigh.Features twill, stretch for performance."
    },
    {
        _id: 24,
        name: "Eddie Bauer Men's Guide Summer Pro Shorts",
        image: "/images/m.shorts/bubbles.jpg",
        price: 15,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Available in Regular and Tall sizes. Active Fit: An athletic fit. Close to the body without restricting mobility. Average inseam: 12 inches."
    },
    {
        _id: 25,
        name: "HUK Men's Next Level 10.5, Quick-Drying Performance Fishing Shorts with UPF 30+ Sun Protection",
        image: "/images/m.shorts/green.jpg",
        price: 60,
        size: "L",
        color: "Green",
        countInStock: 20,
        description: "Huk Uniting anglers through performance-engineered, technical gear designed to fuel your passion and pursuit no matter when, where or how you fish."
    },
    {
        _id: 26,
        name: "LEE Men's Dungarees New Belted Wyoming Outdoor Short",
        image: "/images/m.shorts/orange.jpg",
        price: 45,
        size: "L",
        color: "Orange",
        countInStock: 20,
        description: "Loose fit. With a loose fit through the shorts, these outdoor shorts sit at the waist for natural comfort."
    },
    {
        _id: 27,
        name: "Eddie Bauer Men's Guide Pro Shorts",
        image: "/images/m.shorts/tan.jpg",
        price: 45,
        size: "M",
        color: "Tan",
        countInStock: 20,
        description: "Material: 94% nylon/6% spandex. Care: Machine wash cold, delicate, with like colors. Do not bleach."
    },
    {
        _id: 28,
        name: "PS Paul Smith Men's Shorts",
        image: "/images/m.shorts/white.jpg",
        price: 30,
        size: "L",
        color: "White",
        countInStock: 20,
        description: "Shell: 100% cotton.Fabric: Mid-weight, non-stretch weave.Wash cold."
    },

    //------------------------Mens Sneakers---------------------------------
    {
        _id: 29,
        name: "Lamincoa Men's Tennis Shoes Lightweight Athletic Sneakers",
        image: "/images/m.sneakers/black.jpg",
        price: 30,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "Lightweight and Breathable Upper mesh textile upper,our mens fashion sneaker has good circulation system to keep your feet dry and cool."
    },
    {
        _id: 30,
        name: "adidas Originals Men's I-5923 Shoe",
        image: "/images/m.sneakers/grey.jpg",
        price: 70,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Stretchy mesh upper with suede overlays.Distinctive Boost midsole.Lace closure.Snug Fit."
    },
    {
        _id: 31,
        name: "Jordan 13 Retro",
        image: "/images/m.sneakers/purple.jpg",
        price: 255,
        size: "L",
        color: "White",
        countInStock: 20,
        description: "The Air Jordan 13 is the 2020 release of the beloved original colorway.Purple nylon Jumpman detailing can be found on the throat. White midsole walls contrast the colorful upper."
    },
    {
        _id: 32,
        name: "Balensiaga 90 BeTrue CJ5482 100 Black/Rainbow",
        image: "/images/m.sneakers/rainbow.jpg",
        price: 530,
        size: "L",
        color: "Rainbow",
        countInStock: 20,
        description: "True to size. Delicate detail insole. Comfortable high performance."
    },
    {
        _id: 33,
        name: "Wonesion Mens Breathable Walking Tennis Running Shoes Blade Slip on Casual Fashion Sneakers",
        image: "/images/m.sneakers/run.jpg",
        price: 50,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Perfect choice for any occasion: Running, training, gym, casual walking, workout, and daily wear."
    },
    {
        _id: 34,
        name: "adidas Originals Men's Superstar Shoes",
        image: "/images/m.sneakers/stripe.jpg",
        price: 30,
        size: "L",
        color: "White",
        countInStock: 20,
        description: "100% Nylon.Rubber sole.Moulded sockliner.Colourful shell-toe shoes.Rubber cupsole."
    },
    {
        _id: 35,
        name: "Vans Authentic Skate Shoes 6 (True Grey)",
        image: "/images/m.sneakers/vans.jpg",
        price: 65,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Signature Vans Waffle Outsole.Lace Up Front.Classic Design For Men And Women."
    },
    //-----------------------Mens Tshirts------------------------------------
    {
        _id: 36,
        name: "Men's K87 Short Sleeve T-Shirt (Regular and Big & Tall Sizes)",
        image: "/images/m.t.shirts/black.jpg",
        price: 35,
        size: "M",
        color: "Black",
        countInStock: 20,
        description: ""
    },
    {
        _id: 37,
        name: "Men's Lifestyle Short Sleeve T-shirt",
        image: "/images/m.t.shirts/lion.jpg",
        price: 35,
        size: "M",
        color: "Grey",
        countInStock: 20,
        description: "Super soft, cotton blend fabric provides all day comfort. 100% Polyester."
    },
    {
        _id: 38,
        name: "Men's Short Sleeve 100% Cotton Moon Print Series Graphic Tee Shirt",
        image: "/images/m.t.shirts/moon.jpg",
        price: 40,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Easy pullover styling with a casual crew-neckline.Crew-neck t-shirt with a graphic on front and comfortable cotton construction."
    },
    {
        _id: 39,
        name: "Hanes Men's Graphic T-Shirt - Space Collection",
        image: "/images/m.t.shirts/space.jpg",
        price: 55,
        size: "L",
        color: "Black",
        countInStock: 20,
        description: "Short-sleeve T-shirt featuring Space inspired graphic at front. 90% Cotton, 10% Polyester."
    },
    {
        _id: 40,
        name: "INTO THE AM Men's Graphic Tees - Novelty Graphic T-Shirts with Cool Designs",
        image: "/images/m.t.shirts/sunset.jpg",
        price: 35,
        size: "L",
        color: "Green",
        countInStock: 20,
        description: "This ultra-soft graphic t-shirt is made with a comfortable cotton poly blend that's breathable, shrink resistant."
    },
    {
        _id: 41,
        name: "Mens graphicT-Shirts, Funny T Shirt Customize, Novelty Streetwear Tees",
        image: "/images/m.t.shirts/tiger.jpg",
        price: 40,
        size: "L",
        color: "Lime",
        countInStock: 20,
        description: "Customized personalized T-shirt : You can design your own personalized T-shirt according to your own photos."
    },
    {
        _id: 42,
        name: "Hanes Men's Graphic T-Shirt - Rugged Outdoor Collection",
        image: "/images/m.t.shirts/triangle.jpg",
        price: 25,
        size: "L",
        color: "Grey",
        countInStock: 20,
        description: "Our unique design tees are printed with high-quality inks that won't crack or fade. We have awesome design t-shirts that everyone can love."
    },


    //========================================================================



    //------------------------Womens Dresses-----------------------------------------
    {
        _id: 43 ,
        name: "Women Casual Crew Neck Ruched Sleeveless Tank Shirt Short Mini Dresses",
        image: "/images/w.dresses/blue.jpg",
        price: 40,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Adopts High Quality Fabric Blend Outer Fabric, Soft And Breathable-Will Offer You First-Class Comfort.",
    },
    {
        _id: 44,
        name: "GRACE KARIN Boatneck Sleeveless Vintage Tea Dress",
        image: "/images/w.dresses/classy.jpg",
        price: 88,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Features: Sleeveless, Boatneck, A-Line silhouette, Concealed zipper at back, All kinds of patterns",
    },
    {
        _id: 45,
        name: "BELONGSCI Women's Dress Sweet & Cute V-Neck Bell Sleeve Shift Dress Mini Dress",
        image: "/images/w.dresses/flower.jpg",
        price: 75,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "Material: Made of high quality and high density chiffon with non-elasticity and breathability.",
    },
    {
        _id: 46,
        name: "YESNO Women Casual Loose Bohemian Floral Print Dresses",
        image: "/images/w.dresses/gold.jpg",
        price: 70,
        size: "M",
        color: "Yellow",
        countInStock: 20,
        description: "Occasion: Beach; Vocation; Party; Work; Outside; Trip; Daily Wear; Home Wear",
    },
    {
        _id: 47,
        name: "Women's Swing Dress",
        image: "/images/w.dresses/grey.jpg",
        price: 65,
        size: "M",
        color: "Grey",
        countInStock: 20,
        description: "This versatile sleeveless tank swing dress features a scoop-neckline and a feminine drape for easy, everyday styling",
    },
    {
        _id: 48,
        name: "Nautica Women's Breton Stripes Sleeveless V-Neck Stretch Cotton Polo Dress",
        image: "/images/w.dresses/pink.jpg",
        price: 45,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "95% Cotton, 5% Elastane. Classy, Stylish and Perfect for any formal setting.",
    },
    {
        _id: 49,
        name: "OTTATAT Dresses for Women Casual Summer Dress",
        image: "/images/w.dresses/red.jpeg",
        price: 40,
        size: "M",
        color: "Red",
        countInStock: 20,
        description: "Fashion design keep you cool to wear ,New look, New you！Super Soft and Light weight,Can be easily dress up or dress down",
    },
    //--------------------------Women Pants--------------------------------
    {
        _id: 50,
        name: "Briggs New York Women's Super Stretch Welt Pocket Pull on Career Pant",
        image: "/images/w.pants/army.jpg",
        price: 55,
        size: "M",
        color: "Green",
        countInStock: 20,
        description: "78% Rayon, 19% Nylon, 3% Spandex.Features slimming solution technology.",
    },
    {
        _id: 51,
        name: "Lee Women's Secretly Shapes Regular Fit Straight Leg Pant",
        image: "/images/w.pants/blue.jpg",
        price: 40,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Front dual button closure with zipper, front slant pockets and back welt pockets.",
    },
    {
        _id: 52,
        name: "Calvin Klein Women's Classic Fit Straight Leg Suit Pant",
        image: "/images/w.pants/chill.jpg",
        price: 45,
        size: "M",
        color: "Tan",
        countInStock: 20,
        description: "63% Polyester, 32% Rayon, 5% Spandex.Dry Clean Only.Straight leg.",
    },
    {
        _id: 53,
        name: "Women's Wrinkle Free Relaxed Fit Straight Leg Pant",
        image: "/images/w.pants/green.jpg",
        price: 75,
        size: "M",
        color: "Green",
        countInStock: 20,
        description: "RELAXED FIT. With a relaxed fit and mid rise, these pants are a wardrobe necessity.",
    },
    {
        _id: 54,
        name: "Briggs New York Women's Super Casual Pant",
        image: "/images/w.pants/pink.jpg",
        price: 80,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "Home neccesity, comfy, perfect for athleisure",
    },
    {
        _id: 55,
        name: "Yissang Women's Casual Loose Long Pants",
        image: "/images/w.pants/stripe.jpg",
        price: 120,
        size: "M",
        color: "Grey",
        countInStock: 20,
        description: "Material 65% Cotton,35% Polyester.Only The Waist is Stretchy.",
    },
    {
        _id: 56,
        name: "GRACE KARIN Womens Casual High Waist Pencil Pants",
        image: "/images/w.pants/white.jpg",
        price: 55,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Cropped length (9/10) pencil pants, Back waist is elastic.With belt-fitted loops, matched belt is removable.",
    },

    //-----------------------Women Shoes------------------------------
    {
        _id: 57,
        name: "CentroPoint Women's Fashion Block Boots",
        image: "/images/w.shoes/black.jpg",
        price: 55,
        size: "M",
        color: "Black",
        countInStock: 20,
        description: "All-Day Comfort: Lightly padded soft insole provides adequate support.",
    },
    {
        _id: 58,
        name: "Kodiak Women's Low-Rider Original Chelsea Boot",
        image: "/images/w.shoes/blue.jpg",
        price: 65,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "A must-have in your closet. Suitable for many occasions including daily wear, office, holiday, prom, party, etc.",
    },
    {
        _id: 59,
        name: "Women's Retro Leather Classic Oxford",
        image: "/images/w.shoes/leather.jpg",
        price: 80,
        size: "M",
        color: "Brown",
        countInStock: 20,
        description: "All day Comfort. Oil resistant. Warm and Classic look. Good for all year round. ",
    },
    {
        _id: 60,
        name: "Steve Madden Women's Donddi Sandal",
        image: "/images/w.shoes/sandal.jpg",
        price: 75,
        size: "M",
        color: "Brown",
        countInStock: 20,
        description: "Genuine Leather, Fashionable. Looks great fits true to size.",
    },
    {
        _id: 61,
        name: "Steve Madden 1460 Original Lace-Up Boot",
        image: "/images/w.shoes/stomp.jpg",
        price: 55,
        size: "M",
        color: "Brown",
        countInStock: 20,
        description: "Made with all the classic SM DNA, including grooved sides, heel-loop and TAN stitching",
    },
    {
        _id: 62,
        name: "Collective Women's Aria Leather Ankle Boot",
        image: "/images/w.shoes/suade.jpg",
        price: 99,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "Suede upper and faux suede lining with faux leather sock.Padded insole with 6mm memory foam",
    },
    {
        _id: 63,
        name: "Women's Cloudfoam Pure Running Shoe",
        image: "/images/w.shoes/white.jpg",
        price: 45,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Platform measures approximately 0-3 inches.Cloudfoam memory sockliner and textile lining",
    },


    //-------------------------Women Sneakers----------------------
    {
        _id: 64,
        name: "ASICS Gel-Quantum 180 4 Women's Running Shoe",
        image: "/images/w.sneakers/comfort.jpg",
        price: 45,
        size: "M",
        color: "Black",
        countInStock: 20,
        description: "Complete your run or training time in total confidence with the springy bounce and cushioned support.",
    },
    {
        _id: 65,
        name: "Women's GEL-Venture 5 Casual Shoe",
        image: "/images/w.sneakers/fly.jpg",
        price: 60,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "Removable foam sockliner accommodates orthotics.",
    },
    {
        _id: 66,
        name: "Asics 535 Causual Trainer",
        image: "/images/w.sneakers/hole.jpg",
        price: 70,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Lightweight MD midsole.Lightweight and elastic, provide breathable wear feeling, shock absorbing, abrasion-resistant.",
    },
    {
        _id: 67,
        name: "Coco Chanel Leisure Causual Trainer",
        image: "/images/w.sneakers/oreo.jpg",
        price: 120,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "100% leather. Comfort All Day Long. Styled for performace.",
    },
    {
        _id: 68,
        name: "Nike Women's Running Shoes, Rosa Nero",
        image: "/images/w.sneakers/pink.jpg",
        price: 70,
        size: "M",
        color: "Pink",
        countInStock: 20,
        description: "Designed with lightweight material and a soft foam midsole, built to keep you running in comfort.",
    },
    {
        _id: 69,
        name: "ASICS Women's Gel-Kayano 26 Running Shoes",
        image: "/images/w.sneakers/rainbow.jpg",
        price: 55,
        size: "M",
        color: "Rainbow",
        countInStock: 20,
        description: "ASICS energetic foam formulation that provides supreme bounce thanks to a unique elastomer compound.",
    },
    {
        _id: 70,
        name: "adidas Women's Runfalcon 2.0 Running Shoe",
        image: "/images/w.sneakers/yellow.jpg",
        price: 65,
        size: "M",
        color: "Yellow",
        countInStock: 20,
        description: "Mesh upper for lightweight breathability and no-sew heel for support.",
    },



    //-----------------------------------Women Tops-----------------------------------
    {
        _id: 71,
        name: "Imily Bela Womens Ruffle Sleeve Summer Tops",
        image: "/images/w.tops/blue.jpg",
        price: 65,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Material: 80% COTTON, 20% SPANDEX, comfy to wear all day.",
    },
    {
        _id: 72,
        name: "COACH Tops for Women Spring Blouse",
        image: "/images/w.tops/bright.jpg",
        price: 165,
        size: "M",
        color: "Yellow",
        countInStock: 20,
        description: "Breezy, Comfy all Season Long. 100% Nylon.",
    },
    {
        _id: 73,
        name: "MIHOLL Women’s Long Sleeve Tops Lace Casual Loose Blouses",
        image: "/images/w.tops/button.jpg",
        price: 40,
        size: "M",
        color: "Blue",
        countInStock: 20,
        description: "Casual Long Sleeve tops, crew neck, ballon sleeve with lace arms, loose fit t shirts.",
    },
    {
        _id: 74,
        name: "luvamia Women's Casual Bell Sleeve Crewneck Loose Tops Blouses Shirt",
        image: "/images/w.tops/green.jpg",
        price: 65,
        size: "M",
        color: "Green",
        countInStock: 20,
        description: "Perfect to match with your jeans and your favorite heels to show your personal style.",
    },
    {
        _id: 75,
        name: "Ritual Women's Wide Sleeve Mock Neck Shirt",
        image: "/images/w.tops/open.jpg",
        price: 75,
        size: "M",
        color: "Black",
        countInStock: 20,
        description: "This versatile shirt that features a mock neck and drop sleeves will soon become your go to.",
    },
    {
        _id: 76,
        name: "HOTAPEI Blouses for Women Casual V Neck",
        image: "/images/w.tops/tan.jpg",
        price: 85,
        size: "M",
        color: "Tan",
        countInStock: 20,
        description: "Design: Cute Tops and Blouses，high low hemline. Perfect for Spring/Summer",
    },
    {
        _id: 77,
        name: "Sidefeel Womens Blouse Chiffon Swiss Dot Shirt Tops",
        image: "/images/w.tops/white.jpg",
        price: 40,
        size: "M",
        color: "White",
        countInStock: 20,
        description: "Loose Fit Tunic Tops design, great for taking pictures. perfect for any season.",
    },

]   

module.exports = productData;
